-- CryptoGuard greenfield PostgreSQL schema.
--
-- Replaces storage/schema.sql (SQLite) table-for-table. This is a GREENFIELD
-- schema: there is no data migration from the old SQLite DB. Old data is
-- discarded; the system starts from an empty PostgreSQL database.
--
-- Type mapping (vs schema.sql):
--   INTEGER PRIMARY KEY AUTOINCREMENT  -> id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--                                         (IDENTITY lets explicit ids be inserted for seed rows
--                                          while auto-allocating otherwise)
--   INTEGER (epoch-ms time contract)   -> BIGINT   (analysis_time/open_time/close_time/ts/
--                                         scheduled_time/started_at_ms/lease_until_ms/
--                                         last_updated_ms/last_open_time_fetched/
--                                         last_processed_candle_time/pid/sample_count etc.)
--   REAL                               -> DOUBLE PRECISION
--   TEXT DEFAULT CURRENT_TIMESTAMP     -> TIMESTAMPTZ DEFAULT NOW()
--   TEXT *_json                        -> JSONB (NOT NULL where the SQLite column was NOT NULL;
--                                         literal defaults like '[]' -> '[]'::jsonb)
--   INTEGER 0/1 boolean flags          -> BOOLEAN DEFAULT <bool>
--   TEXT                               -> TEXT (unchanged)
--
-- Time contract preserved: epoch-ms columns stay BIGINT (no semantic change).
-- Timestamp columns become TIMESTAMPTZ; callers that passed ISO strings now
-- pass None (let DEFAULT apply) or a Python datetime.
--
-- Concurrency primitives (used by repository.py / service_manager.py):
--   agent_jobs claim         -> SELECT ... FOR UPDATE SKIP LOCKED (see claim_next_job)
--   analysis_batches seal    -> SELECT ... FOR UPDATE (see claim_next_batch)
--   _service_ownership CAS   -> UPDATE ... WHERE key AND owner_token RETURNING *
--   _analysis_attempt_counter-> INSERT ... ON CONFLICT(batch_id) DO UPDATE SET next_attempt=next_attempt+1 RETURNING next_attempt
--
-- Idempotency: every CREATE TABLE/INDEX uses IF NOT EXISTS so
-- initialize_database() can re-run. The additive migration helpers in
-- migrations.py use ADD COLUMN IF NOT EXISTS / CREATE INDEX IF NOT EXISTS /
-- ON CONFLICT DO NOTHING for the same reason.

-- ── symbols ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS symbols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL UNIQUE,
    market TEXT DEFAULT 'binance_um_futures',
    base_asset TEXT,
    quote_asset TEXT DEFAULT 'USDT',
    category TEXT DEFAULT 'custom',
    enabled BOOLEAN DEFAULT TRUE,
    source TEXT DEFAULT 'user',
    risk_profile TEXT DEFAULT 'auto',
    default_timeframes TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── candles ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS candles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    interval TEXT NOT NULL,
    open_time BIGINT NOT NULL,
    close_time BIGINT NOT NULL,
    open DOUBLE PRECISION NOT NULL,
    high DOUBLE PRECISION NOT NULL,
    low DOUBLE PRECISION NOT NULL,
    close DOUBLE PRECISION NOT NULL,
    volume DOUBLE PRECISION NOT NULL,
    quote_volume DOUBLE PRECISION,
    taker_buy_volume DOUBLE PRECISION,
    taker_buy_quote_volume DOUBLE PRECISION,
    trade_count BIGINT,
    is_closed BOOLEAN DEFAULT TRUE,
    source TEXT DEFAULT 'binance',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(symbol, interval, open_time)
);
CREATE INDEX IF NOT EXISTS idx_candles_symbol_interval_time ON candles(symbol, interval, open_time);
CREATE INDEX IF NOT EXISTS idx_candles_close_time ON candles(symbol, interval, close_time);

-- ── market_profiles ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS market_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    interval TEXT NOT NULL,
    profile_time BIGINT NOT NULL,
    trend_direction TEXT,
    trend_stage TEXT,
    volatility_state TEXT,
    momentum_state TEXT,
    structure_state TEXT,
    smc_state TEXT,
    chanlun_state TEXT,
    profile_json JSONB NOT NULL,
    ga_summary TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(symbol, interval, profile_time)
);

-- ── market_snapshots ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS market_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    analysis_time BIGINT NOT NULL,
    mode TEXT NOT NULL,
    snapshot_json JSONB NOT NULL,
    -- Per-TF data-quality profile (closed_candles_only, missing_timeframes,
    -- status). Computed by ``save_market_snapshot`` after the INSERT (so it
    -- is nullable on the INSERT row, then filled by a second UPDATE); read
    -- by the report/state diagnostics (``SELECT ms.data_quality_json``).
    -- JSONB (NOT TEXT): readers expect an already-decoded dict (P6 contract).
    data_quality_json JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(symbol, analysis_time, mode)
);

-- ── module_analysis_results ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS module_analysis_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    analysis_time BIGINT NOT NULL,
    module TEXT NOT NULL,
    result_json JSONB NOT NULL,
    confidence DOUBLE PRECISION,
    -- FK back to market_snapshots. Set by ``link_module_results_to_snapshot``
    -- AFTER the snapshot INSERT (so nullable on the module row's INSERT, then
    -- filled by UPDATE WHERE symbol+analysis_time). Read by the state-
    -- consistency diagnostics (``load by snapshot_id``). Nullable because a
    -- module result can be persisted before its owning snapshot exists (Phase-1
    -- sink pattern), and is linked in Phase 2.
    snapshot_id BIGINT REFERENCES market_snapshots(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(symbol, timeframe, analysis_time, module)
);

-- ── analysis_states ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS analysis_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    analysis_time BIGINT NOT NULL,
    analysis_time_utc TEXT NOT NULL,
    analysis_mode TEXT NOT NULL,
    timeframes TEXT NOT NULL,
    market_structure_json JSONB NOT NULL,
    trend_clarity_json JSONB NOT NULL,
    no_trade_reason_json JSONB,
    key_levels_json JSONB,
    next_triggers_json JSONB,
    next_analysis_json JSONB,
    breakout_watch_json JSONB,
    trade_permission_json JSONB,
    trade_plan_json JSONB,
    opportunity_watch_recommended BOOLEAN DEFAULT FALSE,
    paper_trade_allowed BOOLEAN DEFAULT FALSE,
    ga_decision_id BIGINT,
    state_json JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_analysis_states_symbol_time ON analysis_states(symbol, analysis_time);

-- ── skill_execution_logs ─────────────────────────────────────────────────
-- 07-14 R8 P2-NEW-1: LAYERED lifecycle. 'prepared' in Phase 1, 'committed'
-- after a successful Phase-2 seal, 'aborted_unsealed' on seal failure,
-- 'aborted' by crash-recovery. NULL (legacy) reads as legacy_committed.
CREATE TABLE IF NOT EXISTS skill_execution_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name TEXT NOT NULL,
    skill_version TEXT NOT NULL,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    analysis_time BIGINT NOT NULL,
    input_summary_json JSONB,
    tool_result_json JSONB NOT NULL,
    ga_interpretation_json JSONB NOT NULL,
    final_result_json JSONB NOT NULL,
    confidence DOUBLE PRECISION,
    commit_state TEXT,
    batch_id TEXT,
    attempt_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_skill_logs_symbol_time ON skill_execution_logs(symbol, timeframe, analysis_time, skill_name);
CREATE INDEX IF NOT EXISTS idx_skill_logs_commit_state_time ON skill_execution_logs(commit_state, analysis_time);

-- ── skill_feedback_memory ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS skill_feedback_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name TEXT NOT NULL,
    skill_version TEXT NOT NULL,
    feedback_type TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_id BIGINT,
    pattern_type TEXT,
    affected_symbols TEXT,
    affected_sides TEXT,
    finding TEXT NOT NULL,
    suggested_adjustment_json JSONB,
    status TEXT DEFAULT 'candidate',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_skill_feedback_status ON skill_feedback_memory(skill_name, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_skill_feedback_pattern ON skill_feedback_memory(pattern_type, status);

-- ── ga_decisions ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ga_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    analysis_time BIGINT NOT NULL,
    analysis_time_utc TEXT NOT NULL,
    decision_type TEXT NOT NULL,
    signal_grade TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    market_bias TEXT,
    trend_stage TEXT,
    decision TEXT NOT NULL,
    skill_result_refs_json JSONB NOT NULL,
    evidence_json JSONB NOT NULL,
    counter_evidence_json JSONB NOT NULL,
    risk_check_json JSONB NOT NULL,
    trade_plan_json JSONB,
    opportunity_watch_json JSONB,
    feishu_actions_json JSONB NOT NULL,
    final_summary TEXT NOT NULL,
    raw_decision_json JSONB NOT NULL,
    analysis_state_id BIGINT,
    snapshot_id BIGINT,
    account_feedback_gate_json JSONB,
    market_regime_gate_json JSONB,
    batch_id TEXT,
    previous_grade TEXT,
    rendered_summary TEXT,
    created_by TEXT DEFAULT 'ga_master_controller',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ga_decisions_symbol_time ON ga_decisions(symbol, analysis_time);
CREATE INDEX IF NOT EXISTS idx_ga_decisions_grade_time ON ga_decisions(signal_grade, analysis_time);
-- Partial index: only sealed/batched decisions (batch_id IS NOT NULL).
CREATE INDEX IF NOT EXISTS idx_ga_decisions_batch ON ga_decisions(batch_id) WHERE batch_id IS NOT NULL;

-- ── analysis_batches ─────────────────────────────────────────────────────
-- 07-13 R6-B (P0-1): whole-batch sealing. NULL claim_ready_at/sealed_at means
-- the producer is still inserting or exact-set validation failed closed;
-- claim_next_batch skips such batches. Set together by the producer after the
-- exact-set check.
CREATE TABLE IF NOT EXISTS analysis_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id TEXT NOT NULL UNIQUE,
    primary_interval TEXT NOT NULL,
    analysis_time BIGINT NOT NULL,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    status TEXT DEFAULT 'running',
    enabled_symbols_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    completed_symbols_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    failed_symbols_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    summary_json JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    claim_ready_at TIMESTAMPTZ,
    sealed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_analysis_batches_status_time ON analysis_batches(status, analysis_time);

-- ── batch_symbol_status ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS batch_symbol_status (
    batch_id  TEXT NOT NULL,
    symbol    TEXT NOT NULL,
    status    TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'completed', 'failed')),
    updated_at TIMESTAMPTZ,
    PRIMARY KEY (batch_id, symbol),
    CONSTRAINT fk_batch_symbol_status_batch
        FOREIGN KEY (batch_id) REFERENCES analysis_batches(batch_id) ON DELETE CASCADE
);

-- ── signals ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    timeframe TEXT,
    direction TEXT,
    trend_stage TEXT,
    strategy_name TEXT,
    strategy_version TEXT,
    strategy_tags TEXT,
    confidence DOUBLE PRECISION,
    score DOUBLE PRECISION,
    signal_grade TEXT,
    alert_level TEXT,
    decision TEXT,
    market_snapshot_id BIGINT,
    trade_plan_json JSONB,
    opportunity_watch_json JSONB,
    ga_reason TEXT,
    risk_notes TEXT,
    status TEXT DEFAULT 'created',
    ga_decision_id BIGINT,
    ga_decision_json JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY(market_snapshot_id) REFERENCES market_snapshots(id)
);

-- ── ad_hoc_analyses ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ad_hoc_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    requested_by TEXT,
    request_text TEXT,
    timeframes TEXT,
    analysis_result_json JSONB NOT NULL,
    ga_summary TEXT,
    has_trade_plan BOOLEAN DEFAULT FALSE,
    signal_id BIGINT,
    status TEXT DEFAULT 'created',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY(signal_id) REFERENCES signals(id)
);

-- ── opportunity_watches ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS opportunity_watches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    direction TEXT,
    watch_reason TEXT,
    watch_condition_json JSONB NOT NULL,
    invalid_condition_json JSONB,
    source_analysis_id BIGINT,
    source_signal_id BIGINT,
    status TEXT DEFAULT 'active',
    expires_at TIMESTAMPTZ,
    triggered_at TIMESTAMPTZ,
    invalidated_reason TEXT,
    last_checked_at TIMESTAMPTZ,
    ga_decision_id BIGINT,
    created_by_user_action BOOLEAN DEFAULT FALSE,
    source_button_action TEXT,
    dedupe_key TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_opportunity_status_symbol ON opportunity_watches(status, symbol);
-- Unique partial dedupe index: only one ACTIVE watch per dedupe_key. NULL
-- dedupe_key rows (non-deduplicated watches) are unconstrained. A terminal
-- watch (triggered/invalidated/expired) releases its dedupe_key so a fresh
-- active watch can be re-created with the same key (P0-2 dedupe contract).
CREATE UNIQUE INDEX IF NOT EXISTS idx_opportunity_watches_dedupe
    ON opportunity_watches(dedupe_key)
    WHERE dedupe_key IS NOT NULL AND status = 'active';

-- ── paper_accounts ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS paper_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name TEXT NOT NULL UNIQUE,
    initial_balance DOUBLE PRECISION NOT NULL,
    current_balance DOUBLE PRECISION NOT NULL,
    equity DOUBLE PRECISION NOT NULL,
    realized_pnl DOUBLE PRECISION DEFAULT 0,
    unrealized_pnl DOUBLE PRECISION DEFAULT 0,
    max_drawdown DOUBLE PRECISION DEFAULT 0,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── paper_orders ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS paper_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id BIGINT,
    ga_decision_id BIGINT,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,
    order_type TEXT NOT NULL,
    entry_price DOUBLE PRECISION,
    trigger_price DOUBLE PRECISION,
    stop_loss DOUBLE PRECISION,
    initial_stop_loss DOUBLE PRECISION,
    take_profit_json JSONB,
    quantity DOUBLE PRECISION,
    risk_percent DOUBLE PRECISION,
    status TEXT DEFAULT 'pending',
    reason TEXT,
    fill_method TEXT,
    source TEXT DEFAULT 'signal_compat',
    risk_check_passed BOOLEAN DEFAULT FALSE,
    last_processed_candle_time BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    filled_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    cancel_reason TEXT,
    invalidated_by_ga_decision_id BIGINT,
    UNIQUE(signal_id),
    FOREIGN KEY(signal_id) REFERENCES signals(id)
);

-- ── paper_trades ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS paper_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,
    entry_price DOUBLE PRECISION,
    exit_price DOUBLE PRECISION,
    stop_loss DOUBLE PRECISION,
    initial_stop_loss DOUBLE PRECISION,
    initial_risk_usdt DOUBLE PRECISION,
    take_profit_json JSONB,
    quantity DOUBLE PRECISION,
    pnl DOUBLE PRECISION,
    pnl_percent DOUBLE PRECISION,
    pnl_r DOUBLE PRECISION,
    max_favorable_excursion DOUBLE PRECISION,
    max_adverse_excursion DOUBLE PRECISION,
    entry_efficiency DOUBLE PRECISION,
    exit_efficiency DOUBLE PRECISION,
    signal_decay_score DOUBLE PRECISION,
    stop_take_path_json JSONB,
    fill_method TEXT,
    close_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    FOREIGN KEY(order_id) REFERENCES paper_orders(id)
);
-- One open trade per order: prevents duplicate open trades on the same order.
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_open_trade_per_order
    ON paper_trades(order_id)
    WHERE closed_at IS NULL;

-- ── paper_positions ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS paper_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,
    entry_price DOUBLE PRECISION NOT NULL,
    current_price DOUBLE PRECISION,
    quantity DOUBLE PRECISION NOT NULL,
    stop_loss DOUBLE PRECISION,
    take_profit_json JSONB,
    unrealized_pnl DOUBLE PRECISION DEFAULT 0,
    unrealized_pnl_pct DOUBLE PRECISION DEFAULT 0,
    max_favorable_excursion DOUBLE PRECISION DEFAULT 0,
    max_adverse_excursion DOUBLE PRECISION DEFAULT 0,
    status TEXT DEFAULT 'open',
    opened_at TIMESTAMPTZ DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_paper_positions_account
        FOREIGN KEY (account_id) REFERENCES paper_accounts(id)
);
CREATE INDEX IF NOT EXISTS idx_paper_positions_account_status ON paper_positions(account_id, status, symbol);

-- ── paper_trade_logs ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS paper_trade_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id BIGINT,
    event_type TEXT NOT NULL,
    symbol TEXT NOT NULL,
    side TEXT,
    price DOUBLE PRECISION,
    quantity DOUBLE PRECISION,
    pnl DOUBLE PRECISION,
    pnl_pct DOUBLE PRECISION,
    reason TEXT,
    event_json JSONB,
    dedupe_key TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_paper_trade_logs_symbol_time ON paper_trade_logs(symbol, created_at);
-- Unique partial dedupe index: idempotent audit logging via direct INSERT.
-- Only dedupe_key-bearing rows are constrained; non-deduplicated logs are free.
CREATE UNIQUE INDEX IF NOT EXISTS idx_paper_trade_logs_dedupe_key
    ON paper_trade_logs(dedupe_key)
    WHERE dedupe_key IS NOT NULL;

-- ── paper_equity_snapshots ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS paper_equity_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts BIGINT NOT NULL,
    account_equity DOUBLE PRECISION NOT NULL,
    unrealized_pnl DOUBLE PRECISION NOT NULL,
    realized_pnl DOUBLE PRECISION NOT NULL,
    margin_used DOUBLE PRECISION,
    open_position_count BIGINT,
    snapshot_json JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── trade_reviews ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS trade_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id BIGINT,
    result TEXT,
    primary_reason TEXT,
    secondary_reasons_json JSONB,
    market_context TEXT,
    mistake_tags TEXT,
    improvement_suggestion TEXT,
    ga_review_json JSONB,
    market_regime_at_loss TEXT,
    evolution_trigger_allowed BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY(trade_id) REFERENCES paper_trades(id)
);

-- ── strategy_versions ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS strategy_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_name TEXT NOT NULL,
    version TEXT NOT NULL,
    status TEXT DEFAULT 'candidate',
    config_json JSONB NOT NULL,
    change_reason TEXT,
    created_from_review_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(strategy_name, version)
);

-- ── strategy_evaluations ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS strategy_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    timeframe TEXT,
    analysis_time BIGINT NOT NULL,
    strategy_name TEXT NOT NULL,
    strategy_version TEXT NOT NULL,
    score DOUBLE PRECISION,
    decision TEXT,
    evidence_json JSONB,
    counter_evidence_json JSONB,
    is_shadow BOOLEAN DEFAULT FALSE,
    snapshot_id BIGINT,
    pnl_r DOUBLE PRECISION,
    ga_decision_id BIGINT,
    paper_trade_id BIGINT,
    shadow_virtual_trade_id BIGINT,
    outcome_source TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
-- One shadow evaluation per (strategy_name, strategy_version, ga_decision_id).
-- Excludes rows explicitly marked 'duplicate' outcome_source.
CREATE UNIQUE INDEX IF NOT EXISTS idx_strategy_evals_shadow_unique
    ON strategy_evaluations(strategy_name, strategy_version, ga_decision_id)
    WHERE is_shadow = TRUE AND COALESCE(outcome_source, '') <> 'duplicate';

-- ── strategy_patches ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS strategy_patches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_name TEXT NOT NULL,
    from_version TEXT NOT NULL,
    candidate_version TEXT NOT NULL,
    patch_json JSONB NOT NULL,
    reason TEXT,
    evidence_json JSONB,
    trigger_id BIGINT,
    status TEXT DEFAULT 'draft',
    backtest_result_json JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── shadow_test_results ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS shadow_test_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_name TEXT NOT NULL,
    candidate_version TEXT NOT NULL,
    active_version TEXT,
    sample_count BIGINT DEFAULT 0,
    active_stats_json JSONB,
    candidate_stats_json JSONB,
    recommendation TEXT,
    status TEXT DEFAULT 'running',
    verdict_runner_run BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── historical_replay_results ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS historical_replay_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    interval TEXT NOT NULL,
    start_time BIGINT NOT NULL,
    end_time BIGINT NOT NULL,
    strategy_versions_json JSONB,
    result_json JSONB NOT NULL,
    export_path TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── self_evolution_runs ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS self_evolution_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status TEXT NOT NULL,
    result_json JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── evolution_triggers ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS evolution_triggers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_type TEXT NOT NULL,
    strategy_name TEXT,
    symbol TEXT,
    trigger_value DOUBLE PRECISION,
    threshold_value DOUBLE PRECISION,
    related_trade_ids TEXT,
    original_related_trade_ids TEXT,
    latest_related_trade_ids TEXT,
    latest_trigger_value DOUBLE PRECISION,
    latest_triggered_at TIMESTAMPTZ,
    market_regime TEXT,
    evolution_allowed BOOLEAN DEFAULT TRUE,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_evolution_triggers_status ON evolution_triggers(status, trigger_type, created_at);

-- ── strategy_memory ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS strategy_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_name TEXT,
    condition_hash TEXT,
    sample_count BIGINT DEFAULT 0,
    win_count BIGINT DEFAULT 0,
    loss_count BIGINT DEFAULT 0,
    avg_rr DOUBLE PRECISION,
    avg_pnl_percent DOUBLE PRECISION,
    notes TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── daily_review_reports ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS daily_review_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_date TEXT NOT NULL UNIQUE,
    summary_json JSONB NOT NULL,
    ga_report TEXT NOT NULL,
    skill_updates_json JSONB,
    evolution_actions_json JSONB,
    pushed_to_feishu BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── scheduler_runs ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS scheduler_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name TEXT NOT NULL,
    scheduled_time BIGINT NOT NULL,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    status TEXT NOT NULL,
    error_message TEXT,
    result_json JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(job_name, scheduled_time)
);

-- ── agent_jobs ────────────────────────────────────────────────────────────
-- Claimed atomically via claim_next_job:
--   UPDATE agent_jobs SET status='running', started_at=NOW()
--   WHERE id = (SELECT id FROM agent_jobs
--               WHERE status='pending' AND scheduled_at <= NOW()
--               ORDER BY priority, scheduled_at, id
--               FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING *;
CREATE TABLE IF NOT EXISTS agent_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type TEXT NOT NULL,
    priority BIGINT DEFAULT 5,
    source TEXT NOT NULL,
    session_id TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    status TEXT DEFAULT 'pending',
    scheduled_at TIMESTAMPTZ DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    error_message TEXT,
    result_json JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    claim_token TEXT,
    lease_until TIMESTAMPTZ,
    defer_count BIGINT NOT NULL DEFAULT 0,
    deferred_at TIMESTAMPTZ,
    batch_id TEXT,
    symbol TEXT,
    CONSTRAINT ck_scheduled_analysis_job_identity CHECK (
        job_type <> 'scheduled_market_analysis'
        OR (batch_id IS NOT NULL AND symbol IS NOT NULL)
    ),
    CONSTRAINT fk_agent_job_batch_symbol
        FOREIGN KEY (batch_id, symbol)
        REFERENCES batch_symbol_status(batch_id, symbol) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_agent_jobs_status_priority ON agent_jobs(status, priority, scheduled_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_jobs_batch_symbol_unique
    ON agent_jobs(batch_id, symbol)
    WHERE job_type='scheduled_market_analysis';

-- Serialize scheduled-job membership changes with seal/claim. A claimant holds
-- the analysis_batches row FOR UPDATE; this trigger waits for that lock and then
-- rejects any post-seal insert or identity rewrite. Together with the composite
-- FK and partial UNIQUE index, the exact batch set is a database invariant, not
-- a JSON-payload convention vulnerable to READ COMMITTED snapshot changes.
CREATE OR REPLACE FUNCTION guard_scheduled_analysis_job_membership()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    ready_at TIMESTAMPTZ;
BEGIN
    IF NEW.job_type <> 'scheduled_market_analysis' THEN
        RETURN NEW;
    END IF;
    SELECT claim_ready_at INTO ready_at
    FROM analysis_batches
    WHERE batch_id = NEW.batch_id
    FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'scheduled analysis batch does not exist'
            USING ERRCODE = '23503';
    END IF;
    IF ready_at IS NOT NULL THEN
        RAISE EXCEPTION 'scheduled analysis batch is already sealed'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_guard_scheduled_analysis_job_membership ON agent_jobs;
CREATE TRIGGER trg_guard_scheduled_analysis_job_membership
BEFORE INSERT OR UPDATE OF job_type, batch_id, symbol, payload_json ON agent_jobs
FOR EACH ROW EXECUTE FUNCTION guard_scheduled_analysis_job_membership();

-- ── task_locks ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS task_locks (
    lock_name TEXT PRIMARY KEY,
    owner TEXT,
    locked_until TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── feishu_events ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS feishu_events (
    event_id TEXT PRIMARY KEY,
    event_type TEXT,
    received_at TIMESTAMPTZ DEFAULT NOW(),
    payload_json JSONB
);

-- ── alert_outbox ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS alert_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_type TEXT NOT NULL,
    symbol TEXT,
    priority BIGINT DEFAULT 5,
    payload_json JSONB NOT NULL,
    status TEXT DEFAULT 'pending',
    retry_count BIGINT DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    last_error TEXT,
    dedupe_key TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_alert_outbox_status_retry ON alert_outbox(status, next_retry_at, priority);
CREATE INDEX IF NOT EXISTS idx_alert_outbox_dedupe ON alert_outbox(dedupe_key, created_at);
-- Partial unique: only pending alerts are deduplicated by dedupe_key. Sent
-- alerts keep their history; new pending rows can reuse the same key (e.g.
-- periodic hourly_summary reports, retry-after-send scenarios).
CREATE UNIQUE INDEX IF NOT EXISTS idx_alert_outbox_dedupe_unique
    ON alert_outbox(dedupe_key)
    WHERE dedupe_key IS NOT NULL AND status = 'pending';

-- ── _migration_state ──────────────────────────────────────────────────────
-- Migration state marker table. Used by additive migration helpers
-- (_apply_stop_loss_adjustment_dedup() etc.) to skip one-shot historical
-- cleanup after the first successful run. Kept so schema_postgres.sql and
-- migrations.py agree on the table shape.
CREATE TABLE IF NOT EXISTS _migration_state (
    key TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ
);

-- ── _service_ownership ────────────────────────────────────────────────────
-- 07-13 R6-F (P1-1): service-ownership lease. A single row (key=
-- 'service_ownership') records the process owning the CryptoGuard service
-- set for this DB. ``start_all_services`` acquires this lease atomically; a
-- live external owner blocks duplicate starts (already_started_external),
-- a stale lease (expired or dead PID) is reclaimable.
-- 07-14 R7-P0-3: ``owner_token`` is a per-process random secret generated at
-- acquire time so heartbeat renewal/reclaim can CAS on key+pid+owner_token
-- (PID alone is unsafe: an OS may recycle a dead PID onto a new process).
CREATE TABLE IF NOT EXISTS _service_ownership (
    key TEXT PRIMARY KEY,
    pid BIGINT NOT NULL,
    started_at_ms BIGINT NOT NULL,
    db_path TEXT NOT NULL,
    release_commit TEXT,
    owner_identity TEXT,
    lease_until_ms BIGINT NOT NULL,
    owner_token TEXT
);

-- ── _analysis_attempt_counter ─────────────────────────────────────────────
-- 07-13 R6-F (R10-P2): atomic per-BATCH attempt counter. Concurrent producers
-- allocate a unique monotonic attempt_id for a (interval, analysis_time) batch
-- via
--   INSERT INTO _analysis_attempt_counter(batch_id, next_attempt)
--   VALUES(%s, 1)
--   ON CONFLICT(batch_id) DO UPDATE SET
--     next_attempt = _analysis_attempt_counter.next_attempt + 1
--   RETURNING next_attempt;
-- One row per batch_id. The row lock (from the ON CONFLICT DO UPDATE write)
-- serializes concurrent allocators on the SAME batch_id: a second producer's
-- UPDATE blocks until the first commits, then re-reads the incremented counter
-- -> each gets a DISTINCT per-batch monotonic integer (the R9-P2 contract the
-- audit relies on). Keyed on batch_id (NOT symbol) so each batch has its own
-- 1,2,3,... sequence, matching cron_scheduler._allocate_attempt_id.
CREATE TABLE IF NOT EXISTS _analysis_attempt_counter (
    batch_id TEXT PRIMARY KEY,
    next_attempt BIGINT NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── alert_failure_log ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS alert_failure_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_outbox_id BIGINT,
    alert_type TEXT,
    symbol TEXT,
    error_message TEXT,
    retry_count BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── config_hot_reload ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS config_hot_reload (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT NOT NULL,
    requested_by TEXT,
    request_text TEXT,
    confirmation_required BOOLEAN DEFAULT TRUE,
    confirmed BOOLEAN DEFAULT FALSE,
    confirmed_at TIMESTAMPTZ,
    status TEXT DEFAULT 'pending',
    applied_at TIMESTAMPTZ,
    audit_summary TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── parquet_archive_runs ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS parquet_archive_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    interval TEXT NOT NULL,
    year_month TEXT NOT NULL,
    path TEXT NOT NULL,
    rows_written BIGINT DEFAULT 0,
    status TEXT NOT NULL,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_parquet_archive_runs_recent ON parquet_archive_runs(created_at, symbol, interval);

-- ── runtime_config ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS runtime_config (
    config_key TEXT PRIMARY KEY,
    value_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── user_feedback ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type TEXT,
    target_id BIGINT,
    feedback_type TEXT,
    feedback_text TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── sop_definitions ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sop_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sop_name TEXT NOT NULL,
    version TEXT NOT NULL,
    module TEXT NOT NULL,
    steps_json JSONB NOT NULL,
    output_schema_json JSONB NOT NULL,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(sop_name, version)
);

-- ── shadow_virtual_trades ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS shadow_virtual_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_name TEXT NOT NULL DEFAULT 'smc_pullback_long',
    candidate_version TEXT NOT NULL,
    ga_decision_id BIGINT NOT NULL,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL DEFAULT 'LONG',
    entry_type TEXT NOT NULL DEFAULT 'market',
    entry_price DOUBLE PRECISION NOT NULL,
    stop_loss DOUBLE PRECISION NOT NULL,
    initial_stop_loss DOUBLE PRECISION NOT NULL,
    take_profit_json JSONB DEFAULT '[]'::jsonb,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    initial_risk_usdt DOUBLE PRECISION DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'pending_entry',
    opened_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    last_processed_candle_time BIGINT,
    max_favorable_excursion DOUBLE PRECISION DEFAULT 0,
    max_adverse_excursion DOUBLE PRECISION DEFAULT 0,
    current_price DOUBLE PRECISION,
    unrealized_pnl_r DOUBLE PRECISION,
    closed_at TIMESTAMPTZ,
    pnl_r DOUBLE PRECISION,
    close_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
-- One non-duplicate shadow virtual trade per (strategy, candidate, decision).
CREATE UNIQUE INDEX IF NOT EXISTS idx_shadow_vt_unique
    ON shadow_virtual_trades(strategy_name, candidate_version, ga_decision_id)
    WHERE COALESCE(status, '') <> 'duplicate';

-- ── backfill_progress ─────────────────────────────────────────────────────
-- R2: backfill_progress tracks the last-open_time fetched per (symbol,
-- interval) so a paged backfill can resume after interruption without
-- re-fetching completed pages. Primary key is (symbol, interval) — one
-- progress row per pair.
CREATE TABLE IF NOT EXISTS backfill_progress (
    symbol TEXT NOT NULL,
    interval TEXT NOT NULL,
    last_open_time_fetched BIGINT,
    last_updated_ms BIGINT,
    PRIMARY KEY (symbol, interval)
);
