"""Probe: parameter adaptation for JSONB / BOOLEAN / TIMESTAMPTZ columns.

Affects ~40+ repository.py sites. Settles:
  J1: a ``json.dumps(...)`` STRING param into a JSONB column - does PG accept
      it, or does it need an explicit ``::jsonb`` cast / psycopg's dict adapter?
  J2: psycopg does NOT auto-adapt Python dict/list to JSONB with ``%s`` - it
      raises ``cannot adapt type 'dict'``. CONSEQUENCE: repository.py MUST keep
      ``json.dumps(...)`` for all JSONB params (it already does - do NOT convert
      them to raw dicts). This test pins the constraint so a future edit doesn't
      regress it.
  B1: a raw Python ``bool`` into a BOOLEAN column (replaces ``1 if x else 0``).
  T1: omitting a TIMESTAMPTZ column (let DEFAULT NOW() apply) vs passing NOW().
  R1: ``RETURNING id`` on an IDENTITY column + ``cur.fetchone()['id']`` shape.
"""

from __future__ import annotations

import json
import unittest

from plugins.crypto_guard.storage import pg_db
from plugins.crypto_guard.tests.pg_fixtures import make_repo


class TestParamAdaptation(unittest.TestCase):
    def setUp(self) -> None:
        self._repo_handle = make_repo(initialize_schema=False)
        with self._repo_handle.conn.transaction():
            self._repo_handle.conn.execute(
                """
                CREATE TABLE _probe (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sym TEXT UNIQUE NOT NULL,
                    tf JSONB NOT NULL DEFAULT '[]'::jsonb,
                    enabled BOOLEAN NOT NULL DEFAULT TRUE,
                    updated_at TIMESTAMPTZ DEFAULT NOW()
                )
                """
            )

    def tearDown(self) -> None:
        self._repo_handle.close()

    def _roundtrip(self, sym: str) -> dict:
        with pg_db.get_conn() as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT * FROM _probe WHERE sym=%s", (sym,))
                row = cur.fetchone()
            conn.rollback()
        return dict(row) if row else {}

    def test_json_string_param_into_jsonb(self) -> None:
        """J1: json.dumps STRING param -> JSONB column."""
        with pg_db.transaction() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "INSERT INTO _probe(sym, tf, enabled) VALUES (%s, %s, %s) "
                    "ON CONFLICT (sym) DO UPDATE SET tf=EXCLUDED.tf",
                    ("J1", json.dumps(["1d", "4h"], ensure_ascii=False), True),
                )
        row = self._roundtrip("J1")
        self.assertEqual(row.get("tf"), ["1d", "4h"])

    def test_python_dict_param_into_jsonb_rejected(self) -> None:
        """J2: psycopg REJECTS a raw dict/list param for a JSONB column.

        ``cannot adapt type 'dict' using placeholder '%s'``. repository.py MUST
        keep ``json.dumps(...)`` for all JSONB params. This test pins the
        constraint: if psycopg ever gains a built-in dict->jsonb adapter and
        this stops raising, the rewrite rule can be relaxed - but until then,
        json.dumps is mandatory.
        """
        with self.assertRaises(Exception) as cm:
            with pg_db.transaction() as conn:
                with conn.cursor() as cur:
                    cur.execute(
                        "INSERT INTO _probe(sym, tf, enabled) VALUES (%s, %s, %s)",
                        ("J2", {"a": 1, "b": [2, 3]}, True),
                    )
        self.assertIn("cannot adapt", str(cm.exception).lower())

    def test_raw_bool_into_boolean(self) -> None:
        """B1: raw Python bool -> BOOLEAN column."""
        with pg_db.transaction() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "INSERT INTO _probe(sym, tf, enabled) VALUES (%s, %s, %s)",
                    ("B1f", "[]", False),
                )
                cur.execute(
                    "INSERT INTO _probe(sym, tf, enabled) VALUES (%s, %s, %s)",
                    ("B1t", "[]", True),
                )
        self.assertFalse(self._roundtrip("B1f")["enabled"])
        self.assertTrue(self._roundtrip("B1t")["enabled"])

    def test_omit_timestamptz_uses_default(self) -> None:
        """T1: omitting updated_at -> DEFAULT NOW() applies."""
        with pg_db.transaction() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "INSERT INTO _probe(sym, tf, enabled) VALUES (%s, %s, %s)",
                    ("T1", "[]", True),
                )
        row = self._roundtrip("T1")
        self.assertIsNotNone(row.get("updated_at"))

    def test_returning_id_on_identity(self) -> None:
        """R1: RETURNING id on IDENTITY column returns the allocated id."""
        with pg_db.transaction() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "INSERT INTO _probe(sym, tf, enabled) VALUES (%s, %s, %s) "
                    "RETURNING id",
                    ("R1", "[]", True),
                )
                new_id = int(cur.fetchone()["id"])
        self.assertGreater(new_id, 0)
        self.assertEqual(self._roundtrip("R1")["id"], new_id)


if __name__ == "__main__":
    unittest.main()
